export const questions = [
  {
    id: 1,
    image: "/memes/doge.jpg",
    question: "Which meme features this iconic Shiba Inu?",
    options: ["Pepe", "Doge", "Drake", "Grumpy"],
    answer: "Doge",
    keywords: ["doge", "shiba"],
  },
  {
    id: 2,
    image: "/memes/drake.jpg",
    question: "Which meme shows Drake approving and rejecting choices?",
    options: ["Doge", "Pepe", "Drake", "NPC"],
    answer: "Drake",
    keywords: ["drake"],
  },
  {
    id: 3,
    image: "/memes/pepe.jpg",
    question: "Which meme is this frog character?",
    options: ["Pepe", "Doge", "Wojak", "Gigachad"],
    answer: "Pepe",
    keywords: ["pepe", "frog"],
  },
  {
    id: 4,
    image: "/memes/distracted.jpg",
    question: "This meme shows a ______ boyfriend?",
    options: ["NPC", "Distracted", "Drake", "Pepe"],
    answer: "Distracted",
    keywords: ["boyfriend", "distracted"],
  },
  {
    id: 5,
    image: "/memes/baigan-aayein-meme.gif",
    question: "This meme is the perfect response when :-",
    options: ["Cooking", "Confused", "Debate", "Shopping"],
    answer: "Confused",
  },
  {
    id: 6,
    image: "/memes/are-kehna-kya-chahte-ho.gif",
    question: "This meme is the official national anthem for:",
    options: ["Students", "Ex", "Nolan", "Everyone"],
    answer: "Everyone",
  },
  {
    id: 7,
    image: "/memes/abhi-maza-aayega-na-bhidu-johnny-lever.gif",
    question: "Which situation fits this meme's energy perfectly?",
    options: ["Drama", "Diet", "Puzzle", "Bank"],
    answer: "Drama",
  },
  {
    id: 8,
    image: "/memes/no-nah.gif",
    question: 'In which situation would you post this "NAHI" meme?',
    options: ["Success", "Friendzone", "Money", "Homework"],
    answer: "Friendzone",
  },
  {
    id: 9,
    image: "/memes/jolly-llb-kon-hai-ye-log-kaha-se-aatey-hai-ye.gif",
    question: "This meme is MOST appropriate in which situation?",
    options: ["Win", "Absurd", "Study", "Cooking"],
    answer: "Absurd",
  },
  {
    id: 10,
    image: "/memes/rasode mein.jpeg",
    question: "The meme “Rasode mein kaun tha?” went viral due to:",
    options: ["Movie", "Remix", "Politics", "Cricket"],
    answer: "Remix",
  }
];